name: Setup Node Environment
description: Setup Node and pnpm, then install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v6.3.0
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
